# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c473233ed68fcd25c201aec97fefa3fbb9364e76ca239f769c05c5e1cf717223846a041ae495036e1f8cb08561d3baebd8200eeb3172451753f9e7c58201632

test:
  secret_key_base: cac4276a32a913c478bd37aea7d8230f84ef1835e7813110b2434f3498defeb58ba67d31a3ea5c1dbf1824b9b02eb6b76d03fa912cb9e7c4fc726f3170d37073

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
